"""empty message

Revision ID: 43aa16282088
Revises: 
Create Date: 2024-03-29 16:37:07.904745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43aa16282088'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso_escolar', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('espacio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('espacio_escolar', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_escolar', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horas_lectivas', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profesor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('tipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_de_asignatura', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuadrante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Asignatura', sa.Integer(), nullable=False),
    sa.Column('Tipo', sa.Integer(), nullable=False),
    sa.Column('Curso', sa.Integer(), nullable=False),
    sa.Column('Grupo', sa.Integer(), nullable=False),
    sa.Column('Horas', sa.Integer(), nullable=False),
    sa.Column('Espacio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Asignatura'], ['asignaturas.id'], ),
    sa.ForeignKeyConstraint(['Curso'], ['curso.id'], ),
    sa.ForeignKeyConstraint(['Espacio'], ['espacio.id'], ),
    sa.ForeignKeyConstraint(['Grupo'], ['grupo.id'], ),
    sa.ForeignKeyConstraint(['Horas'], ['horas.id'], ),
    sa.ForeignKeyConstraint(['Tipo'], ['tipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cuadrante')
    op.drop_table('tipo')
    op.drop_table('profesor')
    op.drop_table('horas')
    op.drop_table('grupo')
    op.drop_table('espacio')
    op.drop_table('curso')
    op.drop_table('asignaturas')
    # ### end Alembic commands ###
