"""empty message

Revision ID: 61bdc1cb5d06
Revises: 
Create Date: 2024-04-01 14:42:42.607224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61bdc1cb5d06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso_escolar', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('espacio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('espacio_escolar', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_escolar', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('hora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hora_lectivas', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('profesor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=True),
    sa.Column('correo', sa.String(length=120), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('tipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_de_asignatura', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('cuadrante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asignaturaId', sa.Integer(), nullable=False),
    sa.Column('tipoId', sa.Integer(), nullable=False),
    sa.Column('cursoId', sa.Integer(), nullable=False),
    sa.Column('grupoId', sa.Integer(), nullable=False),
    sa.Column('horaId', sa.Integer(), nullable=False),
    sa.Column('espacioId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asignaturaId'], ['asignatura.id'], ),
    sa.ForeignKeyConstraint(['cursoId'], ['curso.id'], ),
    sa.ForeignKeyConstraint(['espacioId'], ['espacio.id'], ),
    sa.ForeignKeyConstraint(['grupoId'], ['grupo.id'], ),
    sa.ForeignKeyConstraint(['horaId'], ['hora.id'], ),
    sa.ForeignKeyConstraint(['tipoId'], ['tipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cuadrante')
    op.drop_table('tipo')
    op.drop_table('profesor')
    op.drop_table('hora')
    op.drop_table('grupo')
    op.drop_table('espacio')
    op.drop_table('curso')
    op.drop_table('asignatura')
    # ### end Alembic commands ###
